# Generated by Django 5.1.7 on 2025-03-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('taste', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
